export const SPECIALTIES_LIST = [
    "Adolescent medicine",
    "Aerospace medicine",
    "Allergy and immunology",
    "Anesthesiology",
    "Anatomy",
    "Ayurveda",
    "Bariatrics",
    "Biochemistry",
    "Cardiac anaesthesia",
    "Cardiology",
    "Cardiothoracic surgery",
    "Child and adolescent psychiatry",
    "Clinical neurophysiology",
    "Clinical pharmacology",
    "Colorectal surgery",
    "Community medicine",
    "Dermatology, Venereology and Leprosy",
    "Developmental pediatrics",
    "Emergency medicine",
    "Endocrine surgery",
    "Endocrinology",
    "Family medicine",
    "Forensic Medicine and Toxicology",
    "Forensic psychiatry",
    "Gastroenterology",
    "General medicine",
    "General surgery",
    "Geriatric psychiatry",
    "Geriatrics",
    "Gynecologic oncology",
    "Hand surgery",
    "Head and neck surgery",
    "Health administration",
    "Health education",
    "Hematology",
    "Hematologic pathology",
    "Hepatology",
    "Hepatopancreatobiliary surgery",
    "Homeopathy",
    "Hospital administration",
    "Immunohematology",
    "Infectious diseases",
    "Intensive care medicine",
    "Internal medicine",
    "Interventional radiology",
    "Laboratory medicine",
    "Marine medicine",
    "Maternal-fetal medicine",
    "Medical biochemistry",
    "Medical genetics",
    "Medical oncology",
    "Neonatology",
    "Nephrology",
    "Neuro-anaesthesia",
    "Neurology",
    "Neuropathology",
    "Neuropsychiatry",
    "Neuroradiology",
    "Neurosurgery",
    "Nuclear medicine",
    "Obstetrics and Gynecology",
    "Occupational medicine",
    "Ophthalmology",
    "Oral and maxillofacial surgery",
    "Orthopedic surgery",
    "Otorhinolaryngology",
    "Palliative care",
    "Pathology",
    "Pediatric allergy and immunology",
    "Pediatric cardiology",
    "Pediatric emergency medicine",
    "Pediatric endocrinology",
    "Pediatric gastroenterology",
    "Pediatric hematology and oncology",
    "Pediatric infectious disease",
    "Pediatric nephrology",
    "Pediatric respiratory medicine",
    "Pediatric rheumatology",
    "Pediatric surgery",
    "Pediatrics",
    "Perinatology",
    "Physical medicine and rehabilitation",
    "Physiology",
    "Plastic, reconstructive and aesthetic surgery",
    "Psychiatry",
    "Public health",
    "Pulmonology or Respiratory medicine",
    "Radiation oncology",
    "Radiodiagnosis",
    "Radiology",
    "Radiotherapy",
    "Reproductive endocrinology and infertility",
    "Rheumatology",
    "Siddha",
    "Sports medicine",
    "Surgical gastroenterology",
    "Surgical oncology",
    "Thoracic surgery",
    "Toxicology",
    "Transfusion medicine",
    "Trauma and emergency surgery",
    "Tropical medicine",
    "Unani",
    "Urology",
    "Vascular surgery",
    "Virology",
    "Yoga and Naturopathy"
];
