export const SPECIALTIES_LIST = [
    "Aerospace medicine",
    "Allergy and clinical immunology",
    "Anaesthesiology",
    "Anatomy",
    "Biochemistry",
    "Cardiac anaesthesia",
    "Cardiology",
    "Cardiovascular and thoracic surgery",
    "Child and adolescent psychiatry",
    "Clinical haematology",
    "Clinical immunology and rheumatology",
    "Clinical pharmacology",
    "Critical care medicine",
    "Community medicine",
    "Dermatology, venereology and leprosy",
    "Emergency medicine",
    "Endocrine surgery",
    "Endocrinology",
    "Family medicine",
    "Forensic medicine and toxicology",
    "General medicine",
    "General surgery",
    "Geriatrics",
    "Geriatric mental health",
    "Gynaecologic oncology",
    "Hand surgery",
    "Head and neck surgery",
    "Health administration",
    "Health education",
    "Hepatology",
    "Hepatopancreatobiliary surgery",
    "Hospital administration",
    "Immunohematology",
    "Infectious diseases",
    "Interventional radiology",
    "Laboratory medicine",
    "Marine medicine",
    "Maternal and child health",
    "Medical gastroenterology",
    "Medical genetics",
    "Medical oncology",
    "Neonatology",
    "Nephrology",
    "Neuro-anaesthesia",
    "Neurology",
    "Neurosurgery",
    "Nuclear medicine",
    "Obstetrics and gynaecology",
    "Ophthalmology",
    "Orthopaedics",
    "Otorhinolaryngology",
    "Paediatric anaesthesia",
    "Paediatric cardiology",
    "Paediatric gastroenterology",
    "Paediatric nephrology",
    "Paediatric oncology",
    "Paediatric surgery",
    "Paediatrics",
    "Palliative medicine",
    "Pathology",
    "Paediatric and adolescent endocrinology",
    "Perinatology",
    "Physical medicine and rehabilitation",
    "Physiology",
    "Plastic and reconstructive surgery",
    "Psychiatry",
    "Public health",
    "Pulmonary medicine",
    "Radiation oncology",
    "Radiodiagnosis",
    "Radiology",
    "Radiotherapy",
    "Reproductive medicine",
    "Rheumatology",
    "Sports medicine",
    "Surgical gastroenterology",
    "Surgical oncology",
    "Transfusion medicine",
    "Trauma and emergency surgery",
    "Tropical medicine",
    "Urology",
    "Vascular surgery",
    "Virology",
    "Ayurveda",
    "Yoga and Naturopathy",
    "Unani",
    "Siddha",
    "Homeopathy"
];
