services:
  # 1. NGINX PROXY MANAGER (The Secure Front Door)
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - "80:80" # Let's Encrypt validation & HTTP traffic
      - "443:443" # HTTPS secure traffic
      - "81:81" # NPM Admin Dashboard (accessed via localhost:81)
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt
    networks:
      - hospital_network

  mongodb:
    image: mongo:7
    container_name: hospital_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017" # Exposed for local debugging/tools
    volumes:
      - mongo_data:/data/db
    networks:
      - hospital_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hospital_backend
    restart: unless-stopped
    ports:
      - "5500:5000" # Left open for your local API testing
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - hospital_network
    command: sh -c "node src/seed.js && node src/index.js"

  hospital-portal:
    build:
      context: ./hospital-portal
      dockerfile: Dockerfile
    container_name: hospital_portal
    restart: unless-stopped
    # Public ports removed! NPM will route traffic internally to port 80
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - hospital_network

  admin-dashboard:
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile
    container_name: hospital_admin
    restart: unless-stopped
    # Public ports removed! NPM will route traffic internally to port 80
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - hospital_network

volumes:
  mongo_data:


networks:
  hospital_network:
    driver: bridge
